[package]
name = "pm1-control-model"
version = "0.2.2"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
chassis = { path = "../chassis" }

[features]
default = ["motor"]
motor = []
